forge "https://forgeapi.puppetlabs.com"

mod "reidmv/puppet_certificate"
mod "elasticsearch/logstash"
mod "elasticsearch/elasticsearch"
mod "sensu/sensu"

mod "rtyler/jenkins"

mod "puppetlabs/mcollective", "1.1.6"

mod "thejandroman/kibana3", "0.0.3"

# mod "mbarr/moderninfra",
#   :git => "git://github.com/matthewbarr/moderninfra.git"

#mod "garethr/graphite"

